#######################################################
########## Scoreboard and Economy-System ##############
#######################################################
Config:
  ScoreboardUpdatePeriodInSeconds: 1
  Title: '&6&lScoreboard'
  Scoreboard:
    - '&1'
    - '&aKontostand:'
    - '&8&l> &8%money%'
    - '&2'
    - '&aKills:'
    - '&8&l> &8%kills%'
    - '&3'
    - '&aTode:'
    - '&8&l> &8%deaths%'
    - '&4'
    - '&6IP: &5ip.test.net'