#######################################################
########## Scoreboard and Economy-System ##############
#######################################################
Config:
  # the currency from the economy-system #
  Currency: '$'

  # the state if the scoreboard should update periodic #
  SchedulePeriodicScoreboardUpdating: true

  # the update-period from the scoreboard in seconds #
  ScoreboardUpdatePeriodInSeconds: 1

  # the title from the scoreboard #
  Title: '&6&lScoreboard'

  # the lines from the scoreboard #
  Scoreboard:
    - '&1'
    - '&aKontostand:'
    - '&8&l> &8%money%'
    - '&2'
    - '&aKills:'
    - '&8&l> &8%kills%'
    - '&3'
    - '&aTode:'
    - '&8&l> &8%deaths%'
    - '&4'
    - '&6IP: &5ip.test.net'